spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PWD}
    url: ${MYSQL_URL}

  flyway:
    username: ${MYSQL_USER}
    password: ${MYSQL_PWD}
    url: ${MYSQL_URL}
    table: flyway_schema_history
    enabled: false
    locations: classpath:db/migration
    clean-disabled: true
    baselineOnMigrate: true

node:
  minPayment: 2
  cacheEnable: true
  minFeeLimit: 50000000
  visionApiKey: 8ca51978-72aa-4e0e-9263-22ac222b30b5