# Tomcat
server:
    port: 8060
spring:
    # dev|pro
    profiles:
        active: pro
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    servlet:
        multipart:
            maxRequestSize: 104857600 #100MB

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.vision: info
    com.vision.web.mapper: info

mybatis:
  mapper-locations: classpath:/mapper/**/*Mapper.xml