spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: WAaK2MgAYngRWku35Z
    url: jdbc:mysql://127.0.0.1:3306/oracle?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true

  flyway:
    url: jdbc:mysql://127.0.0.1:3306/oracle?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    user: root
    password: WAaK2MgAYngRWku35Z
    table: flyway_schema_history
    enabled: false
    locations: classpath:db/migration
    clean-disabled: false
    baselineOnMigrate: true

node:
  minPayment: 2
  cacheEnable: true
  minFeeLimit: 50000000
  visionApiKey: set_the_proper_apikey